#
# Copyright (c) 2019-2025 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

schemaVersion: 2.3.0
metadata:
  name: web-terminal-tooling
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi9-latest
      memoryRequest: 1Gi
      memoryLimit: 16Gi
      cpuLimit: '4'
      cpuRequest: '0.5'
      env:
        - name: DOCKER
          value: podman
commands:
  - id: help
    exec:
      label: "List available build options"
      component: tools
      commandLine: bash build.sh --help
      group:
        kind: build 
  - id: build
    exec:
      label: "Build container image"
      component: tools
      commandLine: |
        read -p "ENTER a image name and tag for container builds (default is quay.io/wto/web-terminal-tooling:next): " TARGET_IMG &&
        export WEB_TERMINAL_TOOLING_IMG=${TARGET_IMG}
        bash build.sh -u
      group:
        kind: build
