name: Next Container Build

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: main-container-build

jobs:

  build-next-imgs:
    runs-on: ubuntu-20.04

    outputs:
      git-sha: ${{ steps.git-sha.outputs.sha }}

    steps:
    - name: Checkout devworkspace-operator source code
      uses: actions/checkout@v2

    - name: Set output for Git short SHA
      id: git-sha
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

    - name: Cache tooling binaries
      uses: actions/cache@v2
      id: cache-tooling-binaries
      with:
        path: ./container-root-x86_64.tgz
        key: ${{ hashFiles('tooling_versions.env') }}

    - name: Download tooling binaries
      if: steps.cache-tooling-binaries.outputs.cache-hit != 'true'
      run: |
        ./get-sources.sh

    - name: Login to quay.io
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io

    - name: Build and push images to quay.io
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          quay.io/wto/web-terminal-tooling:next
          quay.io/wto/web-terminal-tooling:sha-${{ steps.git-sha.outputs.sha }}
